config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :bookings

  resources :discounts

  resources :restaurants

  root 'home#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :discount
  belongs_to :user
end

app/models/discount.rb
class Discount < ActiveRecord::Base

  belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :discounts

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name #if there is a name
      user.image = auth.info.image
      user.uid = auth.uid
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:time, :restaurant_id, :date, :num_person, :discount_id, :user_id)
    end
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  # GET /discounts
  # GET /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1
  # GET /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
    @names = Restaurant.all.pluck(:name)
  end

  # POST /discounts
  # POST /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to @discount, notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1
  # PATCH/PUT /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to @discount, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1
  # DELETE /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_params
      params.require(:discount).permit(:restaurant_id, :start_time, :amount)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user, notice: "Signed in!"
    else
      redirect_to new_user_registration_url
    end
  end
  
  alias_method :facebook, :all

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :cuisine, :address, :district, :phone, :lat, :long, :description, :rating, :price_range, :img_url1, :img_url2, :img_url3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for @booking, :html => { :class => "form-horizontal booking" } do |f| %>

  <%= f.error_notification %>

  <%= f.association :restaurant %>
  <%= f.input :date %>
  <%= f.input :num_person, in: 1..20 %>
  <%= f.label :discount_id %>
  <%= f.collection_select :discount_id, Discount.all, :id, :amount, hint: "this is a test hint" %>
  <p></p>
  <%= f.association :discount, member: Discount.all %>
  <%= f.label :user_id %>
  <%= f.collection_select :user_id, User.all, :id, :name %>

  <br />
  <br />
  <%= f.error :base %>
  <%= f.button :submit, :class => 'btn btn-primary' %>

<% end %>

app/views/bookings/edit.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookings/index.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:restaurant_id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:num_person) %></th>
      <th><%= model_class.human_attribute_name(:discount_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to booking.id, booking_path(booking) %></td>
        <td><%= booking.restaurant_id %></td>
        <td><%= booking.date %></td>
        <td><%= booking.num_person %></td>
        <td><%= booking.discount_id %></td>
        <td><%= booking.user_id %></td>
        <td><%=l booking.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_booking_path(booking), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      booking_path(booking),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_booking_path,
            :class => 'btn btn-primary' %>

app/views/bookings/new.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookings/show.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:restaurant_id) %>:</strong></dt>
  <dd><%= @booking.restaurant_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @booking.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_person) %>:</strong></dt>
  <dd><%= @booking.num_person %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount_id) %>:</strong></dt>
  <dd><%= @booking.discount_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @booking.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bookings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_booking_path(@booking), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              booking_path(@booking),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/discounts/_form.html.erb
<%= simple_form_for @discount, :html => { :class => "form-horizontal discount" } do |f| %>

  <%= f.error_notification %>

  <%= f.association :restaurant %>
  <%= f.input :start_time %>
  <%= f.input :amount %>

  <br />
  <%= f.error :base %>
  <%= f.button :submit, :class => 'btn btn-primary' %>

<% end %>

app/views/discounts/edit.html.erb
<%- model_class = Discount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/discounts/index.html.erb
<%- model_class = Discount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:restaurant_id) %></th>
      <th><%= model_class.human_attribute_name(:restaurant_id) %></th>
      <th><%= model_class.human_attribute_name(:start_time) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @discounts.each do |discount| %>
      <tr>
        <td><%= link_to discount.id, discount_path(discount) %></td>
        <td><%= discount.restaurant_id %></td>
        <td><%= discount.start_time %></td>
        <td><%= discount.amount %></td>
        <td><%=l discount.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_discount_path(discount), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      discount_path(discount),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_discount_path,
            :class => 'btn btn-primary' %>

app/views/discounts/new.html.erb
<%- model_class = Discount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/discounts/show.html.erb
<%- model_class = Discount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:restaurant_id) %>:</strong></dt>
  <dd><%= @discount.restaurant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_time) %>:</strong></dt>
  <dd><%= @discount.start_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @discount.amount %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              discounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_discount_path(@discount), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              discount_path(@discount),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<div class="row text-center">
  <h4>
    Eat at
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Tsim Tsa Tsui <i class="fa fa-caret-down fa-lg"></i>
  </button>

  <!-- Modal -->
  <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Select district:</h4>
        </div>
        <div class="modal-body">
        <div class="list-group">
          <a href="#" class="list-group-item active">Tsim Tsa Tsui</a>
            <a href="#" class="list-group-item">Jordan</a>
            <a href="#" class="list-group-item">Central</a>
            <a href="#" class="list-group-item">Sheung Wan</a>
            <a href="#" class="list-group-item">Causeway Bay</a>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save choice</button>
        </div>
      </div>
    </div>
  </div>

    or search nearby <button type="button" class="btn btn-warning"><i class="fa fa-map-marker fa-lg"></i></button>
  </h4>

</div>

<div class="row" ng-controller="HomeCtrl">

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

    <div class="panel panel-default" ng-repeat="r in restaurants">
      <div class="panel-heading" role="tab" id="heading{{ r.id }}">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ r.id }}" aria-expanded="true" aria-controls="collapse{{ r.id }}">
            {{ r.name }} <span class="pull-right">Cuisine: {{ r.cuisine }}</span>
          </a>
        </h4>
      </div>
      <div id="collapse{{ r.id }}" class="panel-collapse collapse" ng-class="getClass($index)" role="tabpanel" aria-labelledby="heading{{ r.id }}">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-6">
              <div class="thumbnail">
                <img ng-src="{{ getImage(r.img_url1) }}" alt="" class="img-responsive">
              </div>
            </div>
            <div class="col-xs-6">
              <div class="thumbnail">
                <img ng-src="{{ getImage(r.img_url2) }}" alt="" class="img-responsive">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <span class="pull-right">{{ r.rating }} star rating</span>
              {{ r.district }}, {{ r.address }}
            </div>
          </div>
          <div class="row">
            <div class="more-space col-xs-12">
              <div class="panel panel-success">
                <div class="panel-body">
                  <div class="pull-left text-center">
                    <h5>50% &nbsp; &nbsp; &nbsp; 45% &nbsp; &nbsp; &nbsp; 35%</h5>
                    <div class="btn-group" data-toggle="buttons">
                      <label class="btn btn-success active">
                        <input type="radio" name="options" id="option1" autocomplete="off" checked> 3:30pm
                      </label>
                      <label class="btn btn-success">
                        <input type="radio" name="options" id="option2" autocomplete="off"> 4pm
                      </label>
                      <label class="btn btn-success">
                        <input type="radio" name="options" id="option3" autocomplete="off"> 4:30pm
                      </label>
                    </div>
                  </div>


                  <div class="pull-right text-center">
                    <h5>Choose a time</h5>
                    <button type="button" class="btn btn-danger">
                      Book now <i class="fa fa-chevron-circle-right"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div><!-- .row -->
        </div>
      </div>
    </div><!-- .panel -->

  </div><!-- #accordion.panel-group -->

</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant, :html => { :class => "form-horizontal restaurant" } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :cuisine %>
  <%= f.input :address %>
  <%= f.input :district %>
  <%= f.input :phone %>
  <%= f.input :lat %>
  <%= f.input :lng %>
  <%= f.input :description %>
  <div class = "container">
    <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
    <%= f.input :price_range, collection: 1..5, as: :radio_buttons %>
  </div>
  <%= f.input :img_url1 %>
  <%= f.input :img_url2 %>
  <%= f.input :img_url3 %>

  <br />
  <%= f.error :base %>
  <%= f.button :submit, :class => 'btn btn-primary' %>

<% end %>

app/views/restaurants/edit.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cuisine) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:district) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:lat) %></th>
      <th><%= model_class.human_attribute_name(:lng) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:price_range) %></th>
      <th><%= model_class.human_attribute_name(:img_url1) %></th>
      <th><%= model_class.human_attribute_name(:img_url2) %></th>
      <th><%= model_class.human_attribute_name(:img_url3) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.id, restaurant_path(restaurant) %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.cuisine %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.district %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.lat %></td>
        <td><%= restaurant.lng %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.rating %></td>
        <td><%= restaurant.price_range %></td>
        <td><%= restaurant.img_url1 %></td>
        <td><%= restaurant.img_url2 %></td>
        <td><%= restaurant.img_url3 %></td>
        <td><%=l restaurant.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_restaurant_path(restaurant), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      restaurant_path(restaurant), :class => 'btn btn-success btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      restaurant_path(restaurant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_restaurant_path,
            :class => 'btn btn-primary' %>

app/views/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>